### PR TITLE
Django 4 support

### PR DESCRIPTION
**Pull request by arpadmuller**
Removed the deprecated ifequal and ifnotequal from the templates

### CODE REVIEW

**Review by asd191990 — COMMENTED** [review]
good

**Comment by bdef** [comment]
can this get merged? it's a very simple fix!

**Comment by bdef** [comment]
thanks!

**Comment by bifot** [comment]
please make a release for this

**Comment by shayneoneill** [comment]
Not working. Following the instructions on the wiki I still get this, or is there some other steps to get this working (I really am not 100% on how pip work. I assume it just pulls the master branch of git?)

**Comment by webnard** [comment]
@shayneoneill no, pip gets whatever is published on pypi.org unless you specify a git commit. Until @douglasmiranda publishes a new release, you'll have to pull this in like so in your `requirements.txt` file:

```
bootstrap-admin @ git+https://github.com/douglasmiranda/django-admin-bootstrap.git#3e91bfc10b1e14c145a87d34ce4dd08f74e0f6a2
```

**Comment by shayneoneill** [comment]
Fantastic. Cheers.

**Comment by shayneoneill** [comment]
@douglasmiranda You may want to kick over your CI script on this one. Its a pretty big gotchya

**Pull request merged**
