### PR TITLE
Add backward compatible support for Django 1.9 and Django 2.0

### PR DESCRIPTION
**Pull request by ygneo**

### CODE REVIEW

**Comment by zxh326** [comment]
Test on django 2.0 success

**Comment by ygneo** [comment]
Hi @douglasmiranda 

This PR has been open for a while now. I've follow the contributing instructions in the READM to creat his PR. Is there's anything else I have to do so it can be merged?

Thanks.

**Comment by ygneo** [comment]
:+1:

**Comment by AileenLumina** [comment]
It would be nice if this PR was merged as I want to use django-admin-bootstrap for a Django 2.0 project. :)

**Comment by douglasmiranda** [comment]
Thanks, @ygneo for contributing. Feel free to always contribute.

Would be nice always receive contributions like @zxh326 too, feedbacks about PRs and issues are always appreciated and will help decrease the delay when merging PRs and solving issues.

**Comment by douglasmiranda** [comment]
https://github.com/douglasmiranda/django-admin-bootstrap/releases/tag/0.3.9

**Pull request merged**
