### PR TITLE
Fixing import from Django js out of master branch

### LINKED ISSUE #98: Not Found Code 404 for static/admin/js/prepopulate_init.js and static/admin/js/change_form.js
Hello,

I'm getting status not found for these js files:

static/admin/js/change_form.js and  static/admin/js/prepopulate_init.js 
just looked on source code for django 1.9.8 and these files does not exist.

What am I missing here?

Please help!

### PR DESCRIPTION
**Pull request by alvarojoao**
Hello, 

I'm pushing to resolve #98  for those who does not use Django from master branch.
Basically, the versions  branches does not has the following js files:

`admin/js/popup_response.js`
`admin/js/prepopulate_init.js`
`admin/js/change_form.js`

It's need to fix those imports.
You can see the [change_form.html](https://github.com/django/django/blob/1.9.8/django/contrib/admin/templates/admin/change_form.html) example.

ps other files:

[popup_response.html](https://github.com/django/django/blob/1.9.8/django/contrib/admin/templates/admin/change_form.html)
[prepopulated_fields_js.html](https://github.com/django/django/blob/1.9.8/django/contrib/admin/templates/admin/change_form.html)

### CODE REVIEW

**Comment by alvarojoao** [comment]
@douglasmiranda  Not sure if I made the correct procedure to make a pull request...
Let me know if I have to make the feature branch.

**Comment by douglasmiranda** [comment]
Hey @alvarojoao thanks for your pull request, I'm finally coming back to github.

I'm gonna review this, are you still available for any feedbacks?

**Comment by alvarojoao** [comment]
Yes!! I'm available. Great opportunity to work in this project.  I just made the adjustment to work on django 1.9.

**Comment by douglasmiranda** [comment]
So, I saw the changes, it will work on 1.9 but It wont be updated with the latest django version.

I think I will merge on another branch, create a tag and document on README. Like I said here: https://github.com/django-admin-bootstrap/django-admin-bootstrap/issues/98#issuecomment-279178258

**Pull request closed without merging**
